version: 2
aliases:
  - &install_awscli
    name: Install AWS CLI
    command: |
      sudo apt-get install -y python-pip libyaml-dev python-dev jq
      sudo pip install awscli
jobs:
  build:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn lint

  build_docker_img:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/dashboard-visualizer
    resource_class: large
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - run: *install_awscli
      - run:
          name: login to ECR
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ECR_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_ECR_SECRET_ACCESS_KEY
            eval $(aws --region us-east-1 ecr --no-include-email get-login)

      # The first checkout ensures we have the files needed to restore the cache
      - checkout
      - run:
          name: build & push image
          command: |
            export SHORT_GIT_SHA=$(echo $CIRCLE_SHA1 | cut -c -6)
            docker build -t 657871693752.dkr.ecr.us-east-1.amazonaws.com/blockexplorer:$SHORT_GIT_SHA .
            docker tag 657871693752.dkr.ecr.us-east-1.amazonaws.com/blockexplorer:$SHORT_GIT_SHA 657871693752.dkr.ecr.us-east-1.amazonaws.com/blockexplorer:latest
            docker push 657871693752.dkr.ecr.us-east-1.amazonaws.com/blockexplorer:$SHORT_GIT_SHA
            docker push 657871693752.dkr.ecr.us-east-1.amazonaws.com/blockexplorer:latest

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_docker_img:
          requires:
            - build
          filters:
            branches:
              only:
                - master
